// <auto-generated />
namespace SecureCo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecureCoDatabaseSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecureCoDatabaseSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201706170953142_SecureCo-Database-Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
